# Generated by Django 5.2.3 on 2025-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('title', models.TextField()),
                ('com_description', models.TextField()),
                ('job_details', models.JSONField(blank=True, default=dict)),
                ('job_description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
