# Generated by Django 5.2.3 on 2025-11-02 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0003_job_slug_alter_job_date_alter_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='two_line_des',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
